# climonitor リモート接続用サンプル設定ファイル
# ネットワーク越しに別のマシンのmonitorに接続する場合

[connection]
# 接続タイプ: "grpc" または "unix"
type = "grpc"

# gRPC接続時のバインドアドレス
# monitor: 0.0.0.0:50051 で全インターフェースでリッスン
# launcher: リモートホストのIPアドレス:50051 に接続
grpc_bind_addr = "0.0.0.0:50051"

# gRPC接続時のIP許可リスト（リモート接続時は必須設定）
# セキュリティのため、信頼できるIPアドレスのみを許可してください
grpc_allowed_ips = [
    "192.168.1.0/24",      # ローカルネットワーク
    "10.0.0.0/8",          # プライベートネットワーク
    # "172.16.0.0/12",     # プライベートネットワーク
    # "127.0.0.1",         # ローカルホスト（開発時のみ）
]

[logging]
# 詳細ログを有効にするか（リモート接続時は推奨）
verbose = true

# ログファイルパス（CLIツールの出力を保存）
log_file = "~/.climonitor/remote-climonitor.log"

# 使用例:
# 
# 1. サーバー側（monitorを実行するマシン）:
#    climonitor --config examples/config-remote.toml --live
#
# 2. クライアント側（launcherを実行するマシン）:
#    climonitor-launcher --config examples/config-remote.toml claude
#    
#    または環境変数で指定:
#    export CLIMONITOR_GRPC_ADDR="192.168.1.100:50051"
#    climonitor-launcher claude
#
# 注意: ファイアウォールでポート50051を開放する必要があります