# climonitor リモート接続用サンプル設定ファイル
# ネットワーク越しに別のマシンのmonitorに接続する場合

[connection]
# 接続タイプ: "tcp" または "unix"
type = "tcp"

# TCP接続時のバインドアドレス
# monitor: 0.0.0.0:3001 で全インターフェースでリッスン
# launcher: リモートホストのIPアドレス:3001 に接続
tcp_bind_addr = "0.0.0.0:3001"

[logging]
# 詳細ログを有効にするか（リモート接続時は推奨）
verbose = true

# ログファイルパス（CLIツールの出力を保存）
log_file = "~/.climonitor/remote-climonitor.log"

# 使用例:
# 
# 1. サーバー側（monitorを実行するマシン）:
#    climonitor --config examples/config-remote.toml --live
#
# 2. クライアント側（launcherを実行するマシン）:
#    climonitor-launcher --config examples/config-remote.toml claude
#    
#    または環境変数で指定:
#    export CLIMONITOR_TCP_ADDR="192.168.1.100:3001"
#    climonitor-launcher claude
#
# 注意: ファイアウォールでポート3001を開放する必要があります