# climonitor セキュア設定サンプルファイル
# セキュリティを重視したTCP接続設定

[connection]
# 接続タイプ: "tcp" または "unix"
type = "tcp"

# TCP接続時のバインドアドレス
# セキュリティのため、localhost以外からのアクセスを制限
tcp_bind_addr = "127.0.0.1:3001"

# TCP接続時のIP許可リスト（厳格なセキュリティ設定）
tcp_allowed_ips = [
    "127.0.0.1",           # ローカルホストのみ許可
    # "localhost",         # localhostキーワード（127.0.0.1と::1）
]

[logging]
# 詳細ログを有効にしてセキュリティ監査に活用
verbose = true

# ログファイルに全ての接続試行を記録
log_file = "~/.climonitor/secure-climonitor.log"

# セキュリティのベストプラクティス:
#
# 1. IP許可リストの設定:
#    - 必要最小限のIPアドレスのみを許可
#    - CIDR記法でネットワーク範囲を指定可能（例: 192.168.1.0/24）
#    - 空のリストは全IPを許可するため避ける
#
# 2. バインドアドレスの設定:
#    - ローカルのみ: 127.0.0.1:3001
#    - 特定インターフェース: 192.168.1.100:3001
#    - 全インターフェース: 0.0.0.0:3001（推奨しない）
#
# 3. ファイアウォール設定:
#    - TCP port 3001へのアクセスを制限
#    - 信頼できるホストからのみ接続を許可
#
# 4. ログ監視:
#    - verbose = true でログを有効化
#    - 不正な接続試行をログで監視
#
# 5. Unix socket（推奨）:
#    - ローカル接続のみの場合はUnix socketが最もセキュア
#    - type = "unix", unix_socket_path = "/tmp/climonitor.sock"